# Generated by Django 5.2.4 on 2025-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
