# Generated by Django 5.2.4 on 2025-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_cocktail',
            name='name',
        ),
        migrations.AddField(
            model_name='search_cocktail',
            name='cocktail_name',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='search_cocktail',
            name='ingredient_name',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
    ]
