# Generated by Django 5.2.4 on 2025-08-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_remove_search_cocktail_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('ingredient_name', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('count_ingredient', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='search_cocktail',
            old_name='count',
            new_name='count_cocktail',
        ),
        migrations.RemoveField(
            model_name='search_cocktail',
            name='ingredient_name',
        ),
    ]
