# Generated by Django 5.2.4 on 2025-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_search_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=300)),
                ('drink_name', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('count_drink', models.IntegerField(default=1)),
            ],
        ),
    ]
